USE [master]
GO

/****** Object:  Database [HRSystem]    Script Date: 2016/07/27 2:05:29 PM ******/
CREATE DATABASE [HRSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.NMR1404\MSSQL\DATA\HRSystem.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HRSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.NMR1404\MSSQL\DATA\HRSystem_log.ldf' , SIZE = 560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HRSystem] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HRSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [HRSystem] SET  MULTI_USER 
GO

ALTER DATABASE [HRSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HRSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HRSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HRSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HRSystem] SET  READ_WRITE 
GO


